# Generated by Django 5.2.17 on 2026-09-01 22:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_ubicaciones(apps, schema_editor):
    ObjetoEncontrado = apps.get_model('semana2', 'ObjetoEncontrado')
    Ubicacion = apps.get_model('semana2', 'Ubicacion')

    for objeto in ObjetoEncontrado.objects.all():
        nombre_ubicacion = (objeto.ubicacion or '').strip()
        if not nombre_ubicacion:
            continue

        ubicacion, _ = Ubicacion.objects.get_or_create(nombre=nombre_ubicacion)
        objeto.ubicacion_new = ubicacion
        objeto.save(update_fields=['ubicacion_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('semana2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='objetoencontrado',
            name='ubicacion_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='objetos',
                to='semana2.ubicacion',
            ),
        ),
        migrations.RunPython(migrate_ubicaciones, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='objetoencontrado',
            name='ubicacion',
        ),
        migrations.RenameField(
            model_name='objetoencontrado',
            old_name='ubicacion_new',
            new_name='ubicacion',
        ),
        migrations.AlterField(
            model_name='objetoencontrado',
            name='ubicacion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='objetos',
                to='semana2.ubicacion',
            ),
        ),
    ]
