# Generated by Django 5.2.17 on 2026-09-01 21:56

from datetime import date

from django.db import migrations, models


def seed_objetos(apps, schema_editor):
    ObjetoEncontrado = apps.get_model('semana2', 'ObjetoEncontrado')
    ObjetoEncontrado.objects.bulk_create([
        ObjetoEncontrado(
            nombre='Mochila negra',
            descripcion='Mochila negra con cuadernos y bolígrafos',
            ubicacion='Biblioteca',
            fecha=date(2026, 8, 25),
            contacto='Ana Torres',
        ),
        ObjetoEncontrado(
            nombre='Lentes de sol',
            descripcion='Lentes de sol con marco dorado',
            ubicacion='Patio principal',
            fecha=date(2026, 8, 24),
            contacto='Carlos Mendez',
        ),
        ObjetoEncontrado(
            nombre='Tarjeta de estudiante',
            descripcion='Tarjeta de identificación con código de barras',
            ubicacion='Cafetería',
            fecha=date(2026, 8, 23),
            contacto='María García',
        ),
        ObjetoEncontrado(
            nombre='Llaves',
            descripcion='Manojo de llaves con llavero de color rojo',
            ubicacion='Sala de informática',
            fecha=date(2026, 8, 22),
            contacto='Pedro Rodríguez',
        ),
        ObjetoEncontrado(
            nombre='Auriculares',
            descripcion='Auriculares inalámbricos color blanco',
            ubicacion='Aula 305',
            fecha=date(2026, 8, 21),
            contacto='Laura López',
        ),
        ObjetoEncontrado(
            nombre='Cartera de cuero marrón',
            descripcion='Cartera marrón con documentos de identidad',
            ubicacion='Biblioteca - Segundo piso',
            fecha=date(2026, 8, 20),
            contacto='Juan Pérez - 3012345678',
        ),
        ObjetoEncontrado(
            nombre='Cuaderno rojo',
            descripcion='Cuaderno de 100 hojas, color rojo con líneas',
            ubicacion='Aula 102',
            fecha=date(2026, 8, 19),
            contacto='Sofia Ruiz',
        ),
        ObjetoEncontrado(
            nombre='Teléfono móvil',
            descripcion='Teléfono Samsung color negro con funda azul',
            ubicacion='Patio principal',
            fecha=date(2026, 8, 18),
            contacto='Diego Martínez - diego@email.com',
        ),
        ObjetoEncontrado(
            nombre='Reloj de pulsera',
            descripcion='Reloj de pulsera con correa de cuero negro',
            ubicacion='Cafetería',
            fecha=date(2026, 8, 17),
            contacto='Isabela Corrales',
        ),
        ObjetoEncontrado(
            nombre='Botella de agua',
            descripcion='Botella térmica roja con diseño de flores',
            ubicacion='Cancha de deportes',
            fecha=date(2026, 8, 16),
            contacto='Miguel Henao - 3019876543',
        ),
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('contacto', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Objeto encontrado',
                'verbose_name_plural': 'Objetos encontrados',
                'ordering': ['-fecha', 'nombre'],
            },
        ),
        migrations.RunPython(seed_objetos, reverse_code=migrations.RunPython.noop),
    ]
