# Generated by Django 6.1 on 2026-09-12 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Optometrista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_colegiatura', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Optometrista',
                'verbose_name_plural': 'Optometristas',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('armazon', 'Armazón'), ('luna', 'Luna'), ('lente_contacto', 'Lente de contacto')], max_length=20)),
                ('marca', models.CharField(blank=True, default='', max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.TextField(blank=True, default='')),
                ('antecedentes_familiares', models.TextField(blank=True, default='')),
                ('medicamentos_actuales', models.TextField(blank=True, default='')),
                ('tipo_seguro', models.CharField(blank=True, default='', max_length=100)),
                ('contacto_emergencia', models.CharField(blank=True, default='', max_length=100)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha_medica', to='semana4.cliente')),
            ],
            options={
                'verbose_name': 'Ficha médica',
                'verbose_name_plural': 'Fichas médicas',
            },
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_examen', models.DateField()),
                ('diagnostico', models.CharField(max_length=200)),
                ('esfera_od', models.FloatField(blank=True, null=True)),
                ('cilindro_od', models.FloatField(blank=True, null=True)),
                ('eje_od', models.IntegerField(blank=True, null=True)),
                ('esfera_oi', models.FloatField(blank=True, null=True)),
                ('cilindro_oi', models.FloatField(blank=True, null=True)),
                ('eje_oi', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='semana4.cliente')),
            ],
            options={
                'verbose_name': 'Historial clínico',
                'verbose_name_plural': 'Historiales clínicos',
                'ordering': ['-fecha_examen'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField()),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('entregado', 'Entregado')], default='pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='semana4.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='semana4.producto')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='productos',
            field=models.ManyToManyField(related_name='clientes', through='semana4.Venta', to='semana4.producto'),
        ),
    ]
